# Generated by Django 3.2.3 on 2022-02-20 15:38

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('book_over_pic', models.CharField(max_length=50000)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patrons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('User_photo', models.ImageField(default='User/default.png', upload_to=backend.models.upload_to, verbose_name='Image')),
                ('no_of_books', models.IntegerField(default=0, verbose_name='noofbooks')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_take', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_return', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADD', 'ADD'), ('RETURN', 'RETURN')], default=None, max_length=200, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.patrons')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.inventory')),
            ],
        ),
    ]
