# Generated by Django 3.2.3 on 2021-10-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_photo',
            field=models.ImageField(default='User/default.png', upload_to='User/<django.db.models.fields.CharField>', verbose_name='Image'),
        ),
    ]
