# Generated by Django 3.2.3 on 2021-10-23 11:26

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_users_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_photo',
            field=models.ImageField(default='User/default.png', upload_to=backend.models.upload_to, verbose_name='Image'),
        ),
    ]
