# Generated by Django 3.2.3 on 2021-11-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211030_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_take', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_return', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ADD', 'ADD'), ('RETURN', 'RETURN')], default=None, max_length=200, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.patrons')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.inventory')),
            ],
        ),
    ]
