# Generated by Django 3.2.3 on 2021-11-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.patrons'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.inventory'),
        ),
    ]
