# Generated by Django 3.2.3 on 2021-11-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211103_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.patrons'),
        ),
    ]
